In [1]:
import yfinance as yf
import pandas as pd
import numpy as np
import scipy.stats as sc
import scipy.linalg
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
sentiment = pd.read_csv("sentiment4.csv")
sentiment

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0
...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126

In [3]:
def get_data(stock_name):
    stock = yf.Ticker(stock_name).history(start="2020-02-11", end="2020-10-31") # from 2020-02-11 to 2020-10-30
    dates = []
    for x in range(len(stock)):
        newdate = str(stock.index[x])
        newdate = newdate[0:10]
        dates.append(newdate)
    stock['Date'] = dates
    
    split = []
    i = 0
    for date in sentiment.Date:
        if date in stock.Date:
            split.append(stock.iat[i,6])  # Stock Splits
            i+=1
        else:
            split.append(0)
    
    price = np.zeros(263)
    i = 0
    for date in sentiment.Date:
        if date in stock.Date:
            d = "20" + date[6:] + "-" + date[0:2] + "-" + date[3:5]  
            price[i] = stock[stock.Date == d].Close[0]
        else:
            price[i] = 0
        i+=1
    
    for i in range(1, len(price)):
        if price[i] == 0 :
            if i != len(price)-1:
                next_price = 0
                for j in range(i+1,i+7):
                    if price[j] != 0:
                        next_price = price[j]
                        break
                price[i] = 0.5 * (price[i-1] + next_price)
            else:
                price[i] = price[i-1]
    
    sentiment["Price"] = price
    sentiment["Stock Splits"] = split
    return sentiment

In [4]:
Walmart = get_data('WMT')
pd.DataFrame(Walmart).to_csv(r'C:\Users\suziy\OneDrive\Desktop\WMT_adjclose.csv', index=False)
Walmart

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,113.505219,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,113.947823,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,115.511719,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,115.954330,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,116.810047,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,141.642258,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,142.349655,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,139.529968,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,139.410400,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,138.244675,0

In [5]:
Target = get_data('TGT')
pd.DataFrame(Target).to_csv(r'C:\Users\suziy\OneDrive\Desktop\TGT_adjclose.csv', index=False)
Target

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,114.377464,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,115.769318,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,115.935951,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,114.318642,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,115.235405,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,157.319687,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,156.383545,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,154.571045,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,153.614990,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,151.593353,0

In [6]:
Macy = get_data('M')
pd.DataFrame(Macy).to_csv(r'C:\Users\suziy\OneDrive\Desktop\M_adjclose.csv', index=False)
Macy

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,15.708359,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,16.322866,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,16.073221,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,16.006010,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,15.717959,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,6.750000,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,6.450000,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,6.110000,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,6.200000,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,6.210000,0

In [7]:
Lululemon = get_data('LULU')
pd.DataFrame(Lululemon).to_csv(r'C:\Users\suziy\OneDrive\Desktop\LULU_adjclose.csv', index=False)
Lululemon

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,251.580002,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,253.940002,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,253.860001,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,254.410004,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,256.820007,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,331.600006,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,333.809998,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,329.510010,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,330.149994,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,319.290009,0

In [8]:
Costco = get_data('COST')
pd.DataFrame(Costco).to_csv(r'C:\Users\suziy\OneDrive\Desktop\COST_adjclose.csv', index=False)
Costco

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,300.833282,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,305.132629,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,308.114960,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,308.221497,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,310.032211,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,360.554688,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,362.509644,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,354.962189,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,355.546875,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,348.491699,0

In [9]:
Nordstrom = get_data('JWN')
pd.DataFrame(Nordstrom).to_csv(r'C:\Users\suziy\OneDrive\Desktop\JWN_adjclose.csv', index=False)
Nordstrom

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,37.999599,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,39.213928,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,38.898006,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,39.766788,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,39.603893,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,13.240000,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,12.580000,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,12.360000,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,12.210000,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,12.100000,0

In [10]:
HomeDepot = get_data('HD')
pd.DataFrame(HomeDepot).to_csv(r'C:\Users\suziy\OneDrive\Desktop\HD_adjclose.csv', index=False)
HomeDepot

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,236.070419,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,236.021545,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,236.773804,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,239.382263,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,238.849831,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,274.543030,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,275.338684,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,268.257294,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,268.167786,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,265.263611,0

In [11]:
Kohl = get_data('KSS')
pd.DataFrame(Kohl).to_csv(r'C:\Users\suziy\OneDrive\Desktop\KSS_adjclose.csv', index=False)
Kohl

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,42.852695,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,43.739838,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,43.045551,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,42.881626,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,42.573055,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,22.860001,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,22.139999,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,21.160000,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,21.799999,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,21.290001,0

In [12]:
JCPenney = get_data('JCPNQ')
pd.DataFrame(JCPenney).to_csv(r'C:\Users\suziy\OneDrive\Desktop\JCPNQ_adjclose.csv', index=False)
JCPenney

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,0.71,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,0.74,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,0.72,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,0.71,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,0.71,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,0.18,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,0.15,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,0.15,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,0.15,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,0.13,0

In [13]:
Ulta = get_data('ULTA')
pd.DataFrame(Ulta).to_csv(r'C:\Users\suziy\OneDrive\Desktop\ULTA_adjclose.csv', index=False)
Ulta

,Total_Sentiment,Avg_Sentiment,Vaccine,Death,Shut,Spread,Date,Death_Count_Day,Positive_Count_Day,Price,Stock Splits
0,1.1162,0.085862,0,0,0,0,02/11/20,0,0,293.779999,0
1,-1.3723,-0.098021,2,3,1,1,02/12/20,0,0,299.299988,0
2,-1.3975,-0.093167,0,3,0,0,02/13/20,0,0,297.089996,0
3,0.0919,0.009190,0,1,2,1,02/14/20,0,0,294.570007,0
4,0.0000,0.000000,1,0,0,0,02/15/20,0,0,296.639999,0
...,...,...,...,...,...,...,...,...,...,...,...
258,-2.3450,-0.045096,6,4,3,1,10/26/20,217549,8621330,220.970001,0
259,-6.0231,-0.109511,5,8,2,3,10/27/20,218468,8693413,213.380005,0
260,-2.0074,-0.030883,4,4,8,3,10/28/20,219512,8772165,201.429993,0
261,-2.5717,-0.052484,3,1,6,3,10/29/20,220549,8860888,205.619995,0
262,1.2955,0.143944,1,0,0,1,10/30/20,221496,8958126,206.770004,0